sudo: required
services:
  - docker

before_install:
  - docker build -t nileshdang/multi-docker-react -f ./client/Dockerfile.dev ./client

script:
  - docker run nileshdang/multi-docker-react npm run test -- --coverage

after-success:
  - docker build -t nileshdang/multi-docker-client ./client
  - docker build -t nileshdang/multi-docker-nginx ./nginx
  - docker build -t nileshdang/multi-docker-worker ./worker
  - docker build -t nileshdang/multi-docker-server ./server
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push nileshdang/multi-docker-client
  - docker push nileshdang/multi-docker-worker
  - docker push nileshdang/multi-docker-nginx
  - docker push nileshdang/multi-docker-server
