sudo: required

services:
  - docker

before_install:
  - docker build -t nileshdang/multi-docker-react -f ./client/Dockerfile.dev ./client

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t nileshdang/multi-docker-client ./client
  - docker build -t nileshdang/multi-docker-nginx ./nginx
  - docker build -t nileshdang/multi-docker-worker ./worker
  - docker build -t nileshdang/multi-docker-server ./server
  - docker push nileshdang/multi-docker-client
  - docker push nileshdang/multi-docker-worker
  - docker push nileshdang/multi-docker-nginx
  - docker push nileshdang/multi-docker-server

script:
  - docker run nileshdang/multi-docker-react npm run test -- --coverage